# Generated by Django 2.2.7 on 2019-12-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0008_auto_20191210_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
