# Generated by Django 2.2.7 on 2019-12-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0011_cart2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart2',
            old_name='total',
            new_name='amount',
        ),
    ]
