# Generated by Django 2.2.7 on 2019-12-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0012_auto_20191211_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart2',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
