# Generated by Django 2.2.7 on 2019-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0013_auto_20191211_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart2',
            name='price_many',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cart2',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
