# Generated by Django 2.2.7 on 2019-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0021_product2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2',
            name='category',
            field=models.CharField(choices=[('Poppen', 'Poppen'), ('School', 'School'), ('Educatief', 'Educatief'), ("Auto's", "Auto's")], default=None, max_length=64),
        ),
    ]
