# Generated by Django 2.2.7 on 2019-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0023_product3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3',
            name='category',
            field=models.CharField(choices=[('Poppen', 'Poppen'), ('School', 'School'), ('Educatief', 'Educatief'), ("Auto's", "Auto's")], max_length=64),
        ),
    ]
