# Generated by Django 2.2.7 on 2019-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0024_auto_20191212_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3',
            name='category',
            field=models.CharField(choices=[("Auto's", "Auto's"), ('Educatief', 'Educatief'), ('Knuffels', 'Knuffels'), ('Pistolen en geweren', 'Pistolen en geweren'), ('Poppen', 'Poppen'), ('Bureau-artikelen', 'Bureau-artikelen'), ('Schriften', 'Schriften'), ('Schrijfgerei', 'Schrijfgerei'), ('Baby-artikelen', 'Baby-artikelen'), ('Postzegels', 'Postzegels')], max_length=64),
        ),
    ]
