# Generated by Django 2.2.7 on 2019-12-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0025_auto_20191212_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product2',
            new_name='Product4',
        ),
    ]
