# Generated by Django 2.2.7 on 2019-12-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0026_auto_20191212_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product4',
        ),
    ]
