# Generated by Django 2.2.7 on 2019-12-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0027_auto_20191212_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product3',
            new_name='Product',
        ),
    ]
