# Generated by Django 2.2.7 on 2019-12-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skager', '0029_auto_20191212_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
